// TrickplayIdle — WHEN the seek-preview job (issue #85) is allowed to run, and WHERE a walk of the local
// library picks up (issue #302).
//
// #85 generates a film's preview strip BETWEEN PLAYBACKS: you open a file, the player takes the machine, and
// when you leave the player the job makes the sheets. The manner is right and the trigger is narrow — the
// strip does not exist the first time you watch something, only from the second viewing on. #302 widens the
// TRIGGER (the job may also run on genuine idle, over the whole local library) and deliberately does not
// touch the MANNERS: still one file at a time, still off the GUI thread, still cancelled the instant anything
// else wants the machine, still atomic writes, still the same cache key and the same size bound.
//
// Everything here is PURE and Qt-Core-only, for the same reason Trickplay.h is: this is a decision about
// spending somebody's CPU, their disk and — the part that cannot be taken back — their battery, on work they
// did not ask for at that moment. A decision like that must be readable as one function and drivable over its
// whole input space with no window, no decoder and no hardware. probe_trickplay does exactly that.
//
// TWO PREDICATES, AND THEY ARE SEPARATE ON PURPOSE:
//
//   * mayGenerateForOpenedFile() is #85's trigger, unchanged. Its inputs are the two it has always had —
//     previews on, nothing playing — and NONE of #302's new inputs appear in it. It is stated as a named
//     function precisely so that widening the job onto idle cannot quietly narrow the between-playbacks one:
//     the probe asserts its answer over the entire cross-product of the new inputs and finds it constant.
//   * evaluate() is #302's, and it is strictly narrower. Every condition it adds can only REFUSE.
//
// WHAT "IDLE" MEANS HERE, and what it does not. `userActive` is APP-scoped: it is fed from the app's own
// input funnel (the same one attract mode resets its clock on), so it says "nobody is driving EverythingBox",
// not "nobody is using this computer". The app can be minimised behind a game, a compile or a video call and
// still look perfectly idle to us. There is no portable way to ask the machine that question, and guessing at
// it would be worse than admitting it — so this is the honest limit of the predicate, and it is the single
// biggest reason the setting that enables idle generation defaults to OFF (see Settings::previewIdleScan).
//
// NEVER FROM A TIMER ALONE. A caller polls this on a timer, but the timer is only the cadence; the decision
// is these inputs, every time, including while a walk is already running. A job started on a tick and never
// re-asked would keep the decoder for a whole film after the user pressed play.
#pragma once
#include <QString>
#include <QStringList>
#include <QtGlobal>

namespace TrickplayIdle
{

// Mains / battery / we could not tell. Unknown is a REAL value and not a synonym for either: see
// TrickplayPower.h for which platforms can answer and which cannot, and `evaluate` below for what an
// unanswerable machine gets.
enum class Power
{
    Unknown = 0,
    Mains,
    Battery
};

// Everything the decision is made of. Gathered by the caller (MainWindow) from things it already knows; not
// one of them is read from a global in here.
struct Conditions
{
    bool   previewsEnabled = false;  // Settings::previewCacheMb() > 0 — the feature's own switch (#85)
    bool   idleEnabled     = false;  // Settings::previewIdleScan()   — the idle WALK's switch (#302)
    bool   playing         = false;  // a video, game, emulator or reader is on screen, or music is playing
    bool   scanning        = false;  // a library scan is in flight (video / music / audiobook / book)
    bool   building        = false;  // #248's self-compile tier is compiling. We do not fight it for cores
    bool   userActive      = false;  // the app was driven within the quiet period (see the note above)
    Power  power           = Power::Unknown;
    qint64 cacheBytes      = 0;      // what the preview cache holds now
    qint64 boundBytes      = 0;      // what it is allowed to hold (Settings::previewCacheMb, in bytes)
};

// Why the idle walk may not start. `Go` is the only value that permits it; every other value names the rule
// that fired, so a log line — and the probe — can say WHICH, rather than "no".
enum class Verdict
{
    Go = 0,
    PreviewsOff,    // the whole feature is off (cache size 0). Nothing is generated by any trigger
    IdleOff,        // previews are on, but the user has not asked for the library to be swept
    Playing,        // something is on screen or in the speakers. #85's rule, restated for the wider trigger
    Scanning,       // a library scan owns the disk
    Building,       // a compile owns the cores (#248)
    UserActive,     // somebody is driving the app right now
    OnBattery,      // never. A handheld making thumbnails for a library while unplugged is a bug
    PowerUnknown,   // we could not tell, so we do not spend it — see the note on Power below
    CacheFull       // the bound is reached: STOP, do not evict to make room for uninvited work
};

// The order below is the order the reasons are worth hearing in, and it is asserted in the probe so it cannot
// drift: the switches first (a user who turned this off is told that, not that their disk is full), then the
// three "something else wants the machine" conditions, then power, then the bound.
//
// POWER. `Battery` refuses, which is the issue's own rule. `Unknown` ALSO refuses, and that is a decision
// rather than an oversight: this is uninvited work, so the burden of proof is on us to show it is free. A
// desktop with no battery answers `Mains` (a machine with no battery is on mains by construction), so
// refusing on Unknown costs a real desktop nothing; what it costs is the platforms where we have not written
// the reader, and on those the polite behaviour is to do nothing rather than to guess.
//
// THE BOUND. Reaching it STOPS the walk. It does not evict: eviction exists to make room for what the user
// IS watching (Trickplay::planEviction's keepKey), and letting a library sweep evict a film somebody watched
// last night in order to cache one they have never opened is the cache working against its own owner.
inline Verdict evaluate(const Conditions& c)
{
    if (!c.previewsEnabled)              return Verdict::PreviewsOff;
    if (!c.idleEnabled)                  return Verdict::IdleOff;
    if (c.playing)                       return Verdict::Playing;
    if (c.scanning)                      return Verdict::Scanning;
    if (c.building)                      return Verdict::Building;
    if (c.userActive)                    return Verdict::UserActive;
    if (c.power == Power::Battery)       return Verdict::OnBattery;
    if (c.power != Power::Mains)         return Verdict::PowerUnknown;
    if (c.cacheBytes >= c.boundBytes || c.boundBytes <= 0) return Verdict::CacheFull;
    return Verdict::Go;
}

inline bool mayStart(const Conditions& c) { return evaluate(c) == Verdict::Go; }

// #85's OWN trigger, and the whole of it: previews are on and nothing is playing. It lives here, beside the
// wider one, so that the two can be read against each other — and it takes its two inputs as arguments rather
// than a Conditions, so that a new field cannot be added to Conditions and silently start gating it.
// TrickplayGen::pump() calls this; probe_trickplay drives it across every combination of #302's inputs and
// asserts the answer never moves.
inline bool mayGenerateForOpenedFile(bool previewsEnabled, bool playing)
{
    return previewsEnabled && !playing;
}

// Whether there is room to begin (or to keep going with) another unit of uninvited work. Same rule as the
// CacheFull verdict, exposed on its own because the worker re-asks it between grids: a walk that was inside
// the bound when it started can cross it in the middle of a two-hour film, and the honest response there is
// to stop with the grids it has finished — which are whole, and which the resume point will pick up from if
// the user later frees space.
inline bool hasHeadroom(qint64 cacheBytes, qint64 boundBytes)
{
    return boundBytes > 0 && cacheBytes < boundBytes;
}

// ---- The walk -----------------------------------------------------------------------------------------
//
// RESUMABLE AT TWO LEVELS. Trickplay::resumeGrid already resumes WITHIN a film (the first grid missing). This
// resumes ACROSS the library: a sweep interrupted after the third of ten files continues at the fourth rather
// than starting again at the first.
//
// The cursor is the PATH last handed out, not an index, and the list is walked in sorted order. A path
// survives the library changing underneath the walk in a way an index does not: insert a film alphabetically
// before the cursor and an index-based resume silently skips a file forever, while this one is unaffected.
//
// A cursor that is no longer in the list (the file was deleted or renamed) is not an error and does not
// restart the sweep — the answer is still "the first path after it", which is exactly right.

// The index in `sorted` of the next file to work on, or -1 when the sweep has reached the end. An empty
// cursor starts at the beginning.
inline int nextAfter(const QStringList& sorted, const QString& cursor)
{
    for (int i = 0; i < sorted.size(); ++i)
    {
        if (sorted.at(i).isEmpty()) continue;
        if (cursor.isEmpty() || sorted.at(i) > cursor) return i;
    }
    return -1;
}

// What a candidate's cache directory already holds. The walk asks the disk for this and then asks here.
enum class ItemState
{
    NoSheets = 0,  // nothing generated for this file yet
    Partial,       // some whole grids, but not all of them (an interrupted earlier run)
    Complete       // every grid is on disk: skip it, and skip it without opening a decoder
};

// Already-cached files are skipped. Partial ones are NOT skipped — they are the cheapest work in the library,
// since Trickplay::resumeGrid means only the missing grids are captured.
inline bool needsGeneration(ItemState s) { return s != ItemState::Complete; }

// The end of a sweep. The cursor is cleared rather than pinned at the last file, so the next idle period
// starts again at the top of the library and picks up whatever has been added since. That costs nothing on a
// library that is already done: every file answers Complete, which is a directory listing and a sidecar read,
// and no decoder is ever created.
inline QString advanceCursor(const QStringList& sorted, int justDone)
{
    if (justDone < 0 || justDone >= sorted.size()) return QString();
    return (justDone + 1 >= sorted.size()) ? QString() : sorted.at(justDone);
}

} // namespace TrickplayIdle
