// Hand-built AUDIO FIXTURES, shared by every probe that needs a real tagged file on disk (issue #74).
//
// It lives in a header rather than in one probe because there is now more than one probe that needs the
// same bytes: probe_musictags pins what the READER makes of a tag block, probe_musiclibrary pins what the
// SCAN and the grouping make of a folder full of them. A second, independently written fixture builder
// would be the more expensive mistake of the two — two builders drift, and then a scan probe passes
// against files no tag-reader probe ever agreed were well-formed, which is the same as testing nothing.
//
// EVERY FIXTURE IS BUILT FROM THE CONTAINER SPECS, byte by byte: an ID3v2.4 tag in front of real MPEG audio
// frames, a FLAC stream header with a Vorbis comment block and PICTURE blocks, and an MP4 atom tree with an
// ilst full of iTunes items. Nothing binary is committed and nothing is downloaded, for the same reason
// probe_romhack hand-writes its IPS/BPS patches: a checked-in .mp3 is an opaque blob no reviewer can audit
// and no failure can be read against, and a fixture generated by the code under test proves only that the
// code agrees with itself. Every expected value in a probe is a literal written next to the bytes that
// encode it.
//
// Everything here is `inline` and free of state, so a probe includes it and calls it; nothing is written
// anywhere until writeFixture() is handed a path (and a probe's paths are all under its own scratch
// dataDir(), which goes away at exit).
#pragma once
#include <QByteArray>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QList>
#include <QPair>
#include <QString>
#include <QtGlobal>

// ---------------------------------------------------------------------------------------------------------
// Byte-order helpers. Tag containers disagree about endianness inside the same file — ID3v2 and MP4 are
// big-endian, a Vorbis comment block is little-endian — so each one is spelled out rather than assumed.
// ---------------------------------------------------------------------------------------------------------
inline void appendU32be(QByteArray& b, quint32 v)
{
    b.append(char((v >> 24) & 0xFF)); b.append(char((v >> 16) & 0xFF));
    b.append(char((v >> 8) & 0xFF));  b.append(char(v & 0xFF));
}

inline void appendU24be(QByteArray& b, quint32 v)
{
    b.append(char((v >> 16) & 0xFF)); b.append(char((v >> 8) & 0xFF)); b.append(char(v & 0xFF));
}

inline void appendU16be(QByteArray& b, quint16 v)
{
    b.append(char((v >> 8) & 0xFF)); b.append(char(v & 0xFF));
}

inline void appendU32le(QByteArray& b, quint32 v)
{
    b.append(char(v & 0xFF));         b.append(char((v >> 8) & 0xFF));
    b.append(char((v >> 16) & 0xFF)); b.append(char((v >> 24) & 0xFF));
}

// ID3v2 SYNCHSAFE integer: 28 bits carried 7-at-a-time so no size byte can ever look like a frame sync.
inline void appendSynchsafe(QByteArray& b, quint32 v)
{
    b.append(char((v >> 21) & 0x7F)); b.append(char((v >> 14) & 0x7F));
    b.append(char((v >> 7) & 0x7F));  b.append(char(v & 0x7F));
}

// ---------------------------------------------------------------------------------------------------------
// ID3v2.4 (.mp3)
// ---------------------------------------------------------------------------------------------------------
// Frame: 4-char id, synchsafe size of the payload, two flag bytes, payload. Text payloads lead with the
// encoding byte 0x03 = UTF-8, which is what makes the unicode cases below legal rather than lucky.
inline QByteArray id3Frame(const char* id, const QByteArray& payload)
{
    QByteArray f(id, 4);
    appendSynchsafe(f, quint32(payload.size()));
    f.append(char(0)); f.append(char(0));
    f.append(payload);
    return f;
}

inline QByteArray id3TextFrame(const char* id, const QString& text)
{
    QByteArray payload;
    payload.append(char(0x03));
    payload.append(text.toUtf8());
    return id3Frame(id, payload);
}

// TXXX = a user-defined text frame: encoding, NUL-terminated description, value. ReplayGain lives in these.
inline QByteArray id3TxxxFrame(const QString& description, const QString& value)
{
    QByteArray payload;
    payload.append(char(0x03));
    payload.append(description.toUtf8());
    payload.append(char(0));
    payload.append(value.toUtf8());
    return id3Frame("TXXX", payload);
}

// USLT (unsynchronised lyrics, issue #142 source 2): encoding, a 3-byte ISO-639-2 language code, a
// NUL-terminated description, then the whole sheet as one string. The description is what TagLib folds into
// the property key — empty or "LYRICS" gives the plain "LYRICS" key, anything else gives "LYRICS:<DESC>" —
// so it is a parameter here rather than hard-coded, because both shapes are real files.
inline QByteArray id3UsltFrame(const QString& description, const QString& text,
                               const char* language = "eng")
{
    QByteArray payload;
    payload.append(char(0x03));       // UTF-8
    payload.append(language, 3);
    payload.append(description.toUtf8());
    payload.append(char(0));          // NUL terminating the description
    payload.append(text.toUtf8());
    return id3Frame("USLT", payload);
}

// SYLT (synchronised lyrics): encoding, 3-byte language, a TIMESTAMP FORMAT byte (0x02 = milliseconds,
// 0x01 = MPEG frames, which nothing can convert without the frame rate), a CONTENT TYPE byte (0x01 = lyrics),
// a NUL-terminated description, then repeating {NUL-terminated text, 4-byte big-endian timestamp} pairs.
//
// Both classifying bytes are parameters because the reader is required to REFUSE some of their values: a
// frame-counted SYLT and a chord-chart SYLT are both well-formed frames that are not a millisecond lyric
// sheet, and a fixture that could only ever be built as valid could not prove the refusal happens.
inline QByteArray id3SyltFrame(const QList<QPair<quint32, QString>>& entries,
                               quint8 timestampFormat = 0x02, quint8 contentType = 0x01,
                               const char* language = "eng")
{
    QByteArray payload;
    payload.append(char(0x03));       // UTF-8
    payload.append(language, 3);
    payload.append(char(timestampFormat));
    payload.append(char(contentType));
    payload.append(char(0));          // empty description, NUL-terminated
    for (const auto& e : entries)
    {
        payload.append(e.second.toUtf8());
        payload.append(char(0));      // NUL terminating this fragment's text
        appendU32be(payload, e.first);
    }
    return id3Frame("SYLT", payload);
}

// APIC: encoding, NUL-terminated Latin-1 mime type, picture-type byte (0x03 = front cover), NUL-terminated
// description, then the image bytes.
inline QByteArray id3ApicFrame(const QByteArray& mime, quint8 pictureType, const QByteArray& image)
{
    QByteArray payload;
    payload.append(char(0x03));
    payload.append(mime);
    payload.append(char(0));
    payload.append(char(pictureType));
    payload.append(char(0)); // empty description
    payload.append(image);
    return id3Frame("APIC", payload);
}

inline QByteArray id3v2Tag(const QByteArray& frames)
{
    QByteArray tag("ID3", 3);
    tag.append(char(0x04)); tag.append(char(0x00)); // version 2.4.0
    tag.append(char(0x00));                         // no unsynchronisation, no extended header
    appendSynchsafe(tag, quint32(frames.size()));
    tag.append(frames);
    return tag;
}

// N frames of real MPEG-1 Layer III audio: FF FB = sync + MPEG1 + Layer III + no CRC, 0x90 = 128 kbps at
// 44100 Hz with no padding, 0x00 = stereo. Frame length is 144 * 128000 / 44100 = 417 bytes; the payload is
// silence, which TagLib never decodes — it reads the headers.
//
// The DURATION assertion follows from these numbers alone: with no Xing header TagLib treats the stream as
// CBR and computes (stream bytes * 8 / bitrate). 96 frames * 417 = 40032 bytes -> 40032 * 8 / 128 = 2502 ms
// -> 2 seconds. Hand-computed, not read off a run.
inline const int kMpegFrameCount  = 96;
inline const int kMpegFrameLength = 417;

inline QByteArray mpegAudio()
{
    QByteArray frame;
    frame.append(char(0xFF)); frame.append(char(0xFB)); frame.append(char(0x90)); frame.append(char(0x00));
    frame.append(kMpegFrameLength - 4, char(0));

    QByteArray audio;
    for (int i = 0; i < kMpegFrameCount; ++i)
        audio.append(frame);
    return audio;
}

// ---------------------------------------------------------------------------------------------------------
// FLAC (.flac)
// ---------------------------------------------------------------------------------------------------------
// Metadata block header: one byte of (last-block flag | type), then a 24-bit big-endian body length.
inline QByteArray flacBlock(quint8 type, const QByteArray& body, bool lastBlock)
{
    QByteArray b;
    b.append(char((lastBlock ? 0x80 : 0x00) | type));
    appendU24be(b, quint32(body.size()));
    b.append(body);
    return b;
}

// STREAMINFO, the one mandatory block. Its bit layout is not byte-aligned: sample rate (20 bits), channels−1
// (3), bits-per-sample−1 (5) and total samples (36) share one 64-bit field, so it is assembled as an integer
// and written big-endian. 44100 Hz * 3 = 132300 samples is where the 3-second duration assertion comes from.
inline QByteArray flacStreamInfo(quint32 sampleRate, int channels, int bitsPerSample, quint64 totalSamples)
{
    QByteArray b;
    appendU16be(b, 4096); appendU16be(b, 4096);  // min/max block size
    appendU24be(b, 0);    appendU24be(b, 0);     // min/max frame size, unknown
    const quint64 packed = (quint64(sampleRate) << 44) | (quint64(channels - 1) << 41)
                         | (quint64(bitsPerSample - 1) << 36) | totalSamples;
    for (int shift = 56; shift >= 0; shift -= 8)
        b.append(char((packed >> shift) & 0xFF));
    b.append(16, char(0)); // MD5 of the unencoded audio, all-zero == "not computed"
    return b;
}

// A Vorbis comment block: little-endian length-prefixed vendor string, a count, then that many length-
// prefixed "FIELD=value" strings, all UTF-8.
inline QByteArray flacVorbisComment(const QList<QByteArray>& comments)
{
    const QByteArray vendor("probe_musictags");
    QByteArray b;
    appendU32le(b, quint32(vendor.size()));
    b.append(vendor);
    appendU32le(b, quint32(comments.size()));
    for (const QByteArray& c : comments)
    {
        appendU32le(b, quint32(c.size()));
        b.append(c);
    }
    return b;
}

// A PICTURE block: type, length-prefixed mime and description, the four image dimensions nobody validates,
// then the length-prefixed image bytes. All big-endian, unlike the comment block two functions up.
inline QByteArray flacPicture(quint32 pictureType, const QByteArray& mime, const QByteArray& image)
{
    QByteArray b;
    appendU32be(b, pictureType);
    appendU32be(b, quint32(mime.size()));  b.append(mime);
    appendU32be(b, 0);                     // empty description
    appendU32be(b, 300); appendU32be(b, 300); appendU32be(b, 24); appendU32be(b, 0);
    appendU32be(b, quint32(image.size())); b.append(image);
    return b;
}

// ---------------------------------------------------------------------------------------------------------
// MP4 (.m4a)
// ---------------------------------------------------------------------------------------------------------
inline QByteArray mp4Atom(const QByteArray& name, const QByteArray& body)
{
    QByteArray b;
    appendU32be(b, quint32(8 + body.size()));
    b.append(name);
    b.append(body);
    return b;
}

// The iTunes item names begin with the copyright sign (0xA9) — written as a byte rather than in a string
// literal, where the following letter would be swallowed by the \x escape ("\xA9alb" is one bad character).
inline QByteArray itunesName(const char* threeLetters)
{
    QByteArray n(1, char(0xA9));
    n.append(threeLetters, 3);
    return n;
}

// The `data` atom inside an item: a version/flags word whose low byte is the VALUE TYPE (1 = UTF-8 text,
// 0 = implicit, 13 = JPEG, 14 = PNG), a reserved locale word, then the value.
inline QByteArray mp4DataAtom(quint32 type, const QByteArray& payload)
{
    QByteArray body;
    appendU32be(body, type);
    appendU32be(body, 0);
    body.append(payload);
    return mp4Atom("data", body);
}

inline QByteArray mp4TextItem(const QByteArray& name, const QString& text)
{
    return mp4Atom(name, mp4DataAtom(1, text.toUtf8()));
}

// trkn / disk store BOTH numbers in one implicit-typed value: two reserved bytes, the number, the total.
inline QByteArray mp4PairItem(const QByteArray& name, quint16 number, quint16 total)
{
    QByteArray payload;
    appendU16be(payload, 0);
    appendU16be(payload, number);
    appendU16be(payload, total);
    appendU16be(payload, 0);
    return mp4Atom(name, mp4DataAtom(0, payload));
}

// A freeform ("----") item: a `mean` atom naming the vendor, a `name` atom naming the key, then the value.
// This is how everything outside the fixed iTunes vocabulary — ReplayGain included — is stored in an m4a.
inline QByteArray mp4FreeformItem(const QByteArray& key, const QString& value)
{
    QByteArray meanBody; appendU32be(meanBody, 0); meanBody.append("com.apple.iTunes");
    QByteArray nameBody; appendU32be(nameBody, 0); nameBody.append(key);
    QByteArray body = mp4Atom("mean", meanBody);
    body.append(mp4Atom("name", nameBody));
    body.append(mp4DataAtom(1, value.toUtf8()));
    return mp4Atom("----", body);
}

// ---------------------------------------------------------------------------------------------------------
inline bool writeFixture(const QString& path, const QByteArray& bytes)
{
    QDir().mkpath(QFileInfo(path).absolutePath());
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate))
        return false;
    return f.write(bytes) == bytes.size();
}

// Plausible image headers — enough for a mime sniff to be a real test, and never decoded by anything here.
inline QByteArray jpegBytes()
{
    QByteArray b("\xFF\xD8\xFF\xE0", 4);
    b.append("\x00\x10JFIF", 6);
    b.append(64, 'J');
    b.append("\xFF\xD9", 2);
    return b;
}

inline QByteArray pngBytes()
{
    QByteArray b("\x89PNG\r\n\x1A\n", 8);
    b.append(64, 'P');
    return b;
}


// ---------------------------------------------------------------------------------------------------------
// Whole-file assemblers. The pieces above are the container primitives; these are the two complete files a
// probe actually writes to disk, so that "what a valid .mp3 looks like" is decided once.
// ---------------------------------------------------------------------------------------------------------

// A complete mp3: an ID3v2.4 tag followed by real MPEG frames. Duration is 2 seconds by construction (see
// mpegAudio()), which is what every fixture built through here can be asserted against.
inline QByteArray mp3File(const QByteArray& frames)
{
    return id3v2Tag(frames) + mpegAudio();
}

// A complete m4a around an `ilst` of iTunes items: ftyp, then moov/udta/meta/{hdlr,ilst}.
//
// meta is a "full atom": four bytes of version/flags before its children. hdlr's contents are never read by
// anything here, but iTunes writes one and TagLib's own meta-vs-full-atom detection looks at what follows.
//
// There is NO trak/mdhd, so the file is a tag block rather than an encoded song and TagLib reports a duration
// of 0 for it. That is deliberate and is itself asserted: the reader must say "unknown" rather than invent a
// length. The mp3 and FLAC fixtures pin real durations.
inline QByteArray m4aFile(const QByteArray& ilst)
{
    QByteArray hdlrBody;
    appendU32be(hdlrBody, 0); appendU32be(hdlrBody, 0);
    hdlrBody.append("mdirappl");
    hdlrBody.append(12, char(0));

    QByteArray metaBody;
    appendU32be(metaBody, 0);
    metaBody.append(mp4Atom("hdlr", hdlrBody));
    metaBody.append(mp4Atom("ilst", ilst));

    QByteArray ftypBody("M4A ", 4);
    appendU32be(ftypBody, 512);
    ftypBody.append("M4A mp42isom");

    QByteArray m4a = mp4Atom("ftyp", ftypBody);
    m4a.append(mp4Atom("moov", mp4Atom("udta", mp4Atom("meta", metaBody))));
    return m4a;
}
