// Headless check of the music TAG READER (src/media/AudioTags — issue #74, increment 1): the layer the local
// music library will scan with, browse from, and (issue #141) take its ReplayGain numbers out of.
//
// EVERY FIXTURE IS BUILT BYTE BY BYTE from the container specs — an ID3v2.4 tag in front of real MPEG audio
// frames, a FLAC stream header with a Vorbis comment block and two PICTURE blocks, and an MP4 atom tree with
// an ilst full of iTunes items. Nothing binary is committed and nothing is downloaded, for the same reason
// probe_romhack hand-writes its IPS/BPS patches: a checked-in .mp3 is an opaque blob that no reviewer can
// audit and no failure can be read against, and a fixture generated by the code under test proves only that
// the code agrees with itself. Every expected value below is a literal written next to the bytes that encode
// it. The builders themselves moved to tools/MusicFixtures.h when probe_musiclibrary (issue #74, increment 2)
// needed the same bytes — one builder, two probes, so a scan probe can never disagree with this one about
// what a well-formed file looks like.
//
// What it pins:
//   1. ID3v2 (.mp3): all eight text fields, the embedded APIC cover, ReplayGain from TXXX frames, and the
//      duration TagLib derives from the frames — with ALBUM ARTIST DIFFERENT FROM ARTIST, the compilation
//      case that #74 names as the classic first bug of a music library.
//   2. Vorbis comments (.flac): unicode values round-tripping, ReplayGain with a 0.00 dB album gain (present
//      and zero, which must not read as absent), a track number with no total, a missing album artist falling
//      back to the artist, the duration from STREAMINFO, and the FRONT cover being chosen out of two
//      pictures — with its mime type sniffed from the bytes because the tag left it blank.
//   3. MP4 atoms (.m4a): the ©-prefixed items, aART as album artist, trkn/disk integer PAIRS, the covr
//      picture, and ReplayGain out of a lowercase iTunes freeform atom (the same value that arrives
//      uppercase from an mp3 — the reader has to answer to both spellings).
//   4. A valid file with NO tag block at all is an EMPTY result, not a half-filled one — and still reports
//      its duration, which is not metadata and must not make the result look non-empty.
//   5. Garbage is REFUSED, not crashed on: a truncated MP4, a .flac that is not FLAC, a zero-byte file, a
//      path that does not exist, and a directory.
//
// Prints MUSICTAGS-OK on success; any failure prints MUSICTAGS-FAIL <cond> (line) and exits non-zero.
//
// Isolation: AppPaths::dataDir() is this process's own scratch dir (issue #42), so every fixture is written
// under it and the tree goes away at exit. Nothing is written beside the exe.
#include "AudioTags.h"
#include "AppPaths.h"
#include "MusicFixtures.h"

#include <QByteArray>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QString>
#include <cstdio>

static int g_fails = 0;

#define CHECK(cond)                                                                     \
    do {                                                                                \
        if (!(cond)) { std::printf("MUSICTAGS-FAIL %s (%d)\n", #cond, __LINE__); ++g_fails; } \
    } while (0)

// The fixture builders (ID3v2 / FLAC / MP4 byte assembly, the image blobs and writeFixture) live in
// MusicFixtures.h so probe_musiclibrary builds its scan fixtures from the SAME bytes this probe pins
// the reader against. See that header for why they are hand-written rather than committed.

int main(int argc, char** argv)
{
    QCoreApplication app(argc, argv);

    const QString dir = AppPaths::dataDir() + QStringLiteral("/musictags");
    QDir().mkpath(dir);

    const QByteArray jpeg = jpegBytes();
    const QByteArray png  = pngBytes();

    // --- 1. ID3v2.4 in an mp3: every field, the cover, ReplayGain, duration — and a COMPILATION ------------
    // Album artist deliberately differs from artist. A browse that groups on `artist` would split this album
    // into one album per track, which is the failure #74 calls out; the reader has to keep the two apart.
    {
        QByteArray frames;
        frames.append(id3TextFrame("TIT2", QStringLiteral("Windowlicker")));
        frames.append(id3TextFrame("TPE1", QStringLiteral("Aphex Twin")));       // track artist
        frames.append(id3TextFrame("TPE2", QStringLiteral("Various Artists")));  // ALBUM artist
        frames.append(id3TextFrame("TALB", QStringLiteral("Warp Sampler")));
        frames.append(id3TextFrame("TRCK", QStringLiteral("3/12")));
        frames.append(id3TextFrame("TPOS", QStringLiteral("1/2")));
        frames.append(id3TextFrame("TDRC", QStringLiteral("1999-03-22")));
        frames.append(id3TextFrame("TCON", QStringLiteral("Electronic")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_TRACK_GAIN"), QStringLiteral("-7.15 dB")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_TRACK_PEAK"), QStringLiteral("0.988525")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_ALBUM_GAIN"), QStringLiteral("-6.02 dB")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_ALBUM_PEAK"), QStringLiteral("1.014000")));
        frames.append(id3ApicFrame("image/jpeg", 0x03, jpeg));

        const QString path = dir + QStringLiteral("/compilation.mp3");
        CHECK(writeFixture(path, mp3File(frames)));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == QStringLiteral("Windowlicker"));
        CHECK(t.artist == QStringLiteral("Aphex Twin"));
        CHECK(t.albumArtist == QStringLiteral("Various Artists"));
        CHECK(t.albumArtist != t.artist);                                  // the compilation distinction itself
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Various Artists"));
        CHECK(t.album == QStringLiteral("Warp Sampler"));
        CHECK(t.genre == QStringLiteral("Electronic"));
        CHECK(t.track == 3);
        CHECK(t.trackTotal == 12);
        CHECK(t.disc == 1);
        CHECK(t.discTotal == 2);
        CHECK(t.year == 1999);                                             // out of "1999-03-22"
        CHECK(t.durationSec == 2);                                         // 40032 bytes * 8 / 128 kbps
        CHECK(t.cover.data == jpeg);
        CHECK(t.cover.mimeType == QStringLiteral("image/jpeg"));
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - (-7.15)) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 0.988525) < 1e-9);
        CHECK(t.albumGain.present && qAbs(t.albumGain.value - (-6.02)) < 1e-9);
        CHECK(t.albumPeak.present && qAbs(t.albumPeak.value - 1.014) < 1e-9);
    }

    // --- 2. Vorbis comments in a flac: unicode, no album artist, 0 dB album gain, two pictures -------------
    // The title/artist are Japanese and the album is accented Latin: a tag reader that goes through the
    // platform code page instead of UTF-8 mangles both, and a library indexed off mangled names cannot be
    // searched. ALBUMARTIST is absent on purpose — the fallback to the track artist is the tested behaviour.
    {
        const QString uTitle  = QString::fromUtf8("\xE3\x83\xAD\xE3\x83\x9E\xE3\x83\xB3\xE3\x82\xB9");   // ロマンス
        const QString uArtist = QString::fromUtf8("\xE5\xBA\x83\xE7\x80\xAC\xE9\xA6\x99\xE7\xBE\x8E");   // 広瀬香美
        const QString uAlbum  = QString::fromUtf8("Caf\xC3\xA9 del M\xC3\xA1r");                          // Café del Már

        QList<QByteArray> comments;
        comments << QByteArray("TITLE=") + uTitle.toUtf8();
        comments << QByteArray("ARTIST=") + uArtist.toUtf8();
        comments << QByteArray("ALBUM=") + uAlbum.toUtf8();
        comments << QByteArray("GENRE=J-Pop");
        comments << QByteArray("DATE=1993");
        comments << QByteArray("TRACKNUMBER=5");                        // no total: trackTotal stays 0
        comments << QByteArray("REPLAYGAIN_TRACK_GAIN=+3.20 dB");
        comments << QByteArray("REPLAYGAIN_TRACK_PEAK=0.500000");
        comments << QByteArray("REPLAYGAIN_ALBUM_GAIN=0.00 dB");        // present AND zero
        comments << QByteArray("REPLAYGAIN_ALBUM_PEAK=0.750000");

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), false)); // 132300/44100 = 3 seconds
        flac.append(flacBlock(4, flacVorbisComment(comments), false));
        flac.append(flacBlock(6, flacPicture(4, "image/jpeg", jpeg), false));   // 4 = BACK cover, first
        flac.append(flacBlock(6, flacPicture(3, QByteArray(), png), true));     // 3 = FRONT cover, blank mime

        const QString path = dir + QStringLiteral("/unicode.flac");
        CHECK(writeFixture(path, flac));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == uTitle);
        CHECK(t.artist == uArtist);
        CHECK(t.album == uAlbum);
        CHECK(t.genre == QStringLiteral("J-Pop"));
        CHECK(t.albumArtist.isEmpty());                    // not tagged -> stays empty, never guessed
        CHECK(t.effectiveAlbumArtist() == uArtist);        // ...and the grouping key falls back to the artist
        CHECK(t.track == 5);
        CHECK(t.trackTotal == 0);                          // "5" carries no total
        CHECK(t.disc == 0);
        CHECK(t.year == 1993);
        CHECK(t.durationSec == 3);                         // 132300 samples / 44100 Hz
        CHECK(t.cover.data == png);                        // the FRONT cover, not the back one that came first
        CHECK(t.cover.mimeType == QStringLiteral("image/png")); // sniffed: the PICTURE block's mime was blank
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - 3.20) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 0.5) < 1e-9);
        CHECK(t.albumGain.present && qAbs(t.albumGain.value - 0.0) < 1e-9); // 0 dB is a VALUE, not an absence
        CHECK(t.albumPeak.present && qAbs(t.albumPeak.value - 0.75) < 1e-9);
    }

    // --- 3. MP4 atoms in an m4a: aART, integer pairs, covr, and a LOWERCASE freeform ReplayGain ------------
    // iTunes writes its freeform keys lowercase while ID3v2 TXXX descriptions arrive uppercased, so the same
    // ReplayGain tag has two spellings across two containers and the reader must answer to both.
    {
        QByteArray ilst;
        ilst.append(mp4TextItem(itunesName("nam"), QStringLiteral("Bohemian Rhapsody")));
        ilst.append(mp4TextItem(itunesName("ART"), QStringLiteral("Queen")));
        ilst.append(mp4TextItem("aART", QStringLiteral("Freddie & Friends")));  // album artist != artist again
        ilst.append(mp4TextItem(itunesName("alb"), QStringLiteral("A Night at the Opera")));
        ilst.append(mp4TextItem(itunesName("gen"), QStringLiteral("Rock")));
        ilst.append(mp4TextItem(itunesName("day"), QStringLiteral("1975")));
        ilst.append(mp4PairItem("trkn", 11, 12));
        ilst.append(mp4PairItem("disk", 1, 1));
        ilst.append(mp4Atom("covr", mp4DataAtom(14, png)));                     // 14 = PNG
        ilst.append(mp4FreeformItem("replaygain_track_gain", QStringLiteral("-9.35 dB")));
        ilst.append(mp4FreeformItem("replaygain_track_peak", QStringLiteral("1.030000")));

        // m4aFile() wraps the ilst in ftyp + moov/udta/meta (MusicFixtures.h explains the full-atom layout and
        // the hdlr TagLib's detection looks at). It writes NO trak/mdhd, so this fixture is a tag block rather
        // than an encoded song and durationSec is asserted to be 0 BECAUSE of that — the reader must report
        // "unknown" rather than invent a length, and the two containers above already pin a real duration.
        const QString path = dir + QStringLiteral("/opera.m4a");
        CHECK(writeFixture(path, m4aFile(ilst)));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == QStringLiteral("Bohemian Rhapsody"));
        CHECK(t.artist == QStringLiteral("Queen"));
        CHECK(t.albumArtist == QStringLiteral("Freddie & Friends"));
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Freddie & Friends"));
        CHECK(t.album == QStringLiteral("A Night at the Opera"));
        CHECK(t.genre == QStringLiteral("Rock"));
        CHECK(t.track == 11);
        CHECK(t.trackTotal == 12);
        CHECK(t.disc == 1);
        CHECK(t.discTotal == 1);
        CHECK(t.year == 1975);
        CHECK(t.durationSec == 0);                          // no audio track in the fixture; see above
        CHECK(t.cover.data == png);
        CHECK(t.cover.mimeType == QStringLiteral("image/png"));
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - (-9.35)) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 1.03) < 1e-9);
        CHECK(!t.albumGain.present);                        // not tagged -> absent, not 0
        CHECK(!t.albumPeak.present);
    }

    // --- 4. A valid file with NO tags is an EMPTY result --------------------------------------------------
    // Both halves matter: nothing is invented for the fields, and the duration that IS readable does not make
    // the result look tagged. The scan uses isEmpty() to decide a file needs its filename fallback.
    {
        const QString mp3 = dir + QStringLiteral("/untagged.mp3");
        CHECK(writeFixture(mp3, mpegAudio()));
        const AudioTags::Tags t = AudioTags::read(mp3);
        CHECK(t.isEmpty());
        CHECK(t.title.isEmpty() && t.artist.isEmpty() && t.albumArtist.isEmpty() && t.album.isEmpty());
        CHECK(t.track == 0 && t.disc == 0 && t.year == 0);
        CHECK(t.cover.isNull());
        CHECK(!t.trackGain.present && !t.albumGain.present);
        CHECK(t.durationSec == 2);          // readable, and still not metadata

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), true));
        const QString flacPath = dir + QStringLiteral("/untagged.flac");
        CHECK(writeFixture(flacPath, flac));
        const AudioTags::Tags f = AudioTags::read(flacPath);
        CHECK(f.isEmpty());
        CHECK(f.durationSec == 3);
    }

    // --- 5. Broken input is refused, never crashed on -----------------------------------------------------
    // A library scan walks whatever is on the disk: half-finished downloads, files renamed by hand, an error
    // page saved with an .mp3 on the end. Every one of these has to come back empty and come back at all.
    {
        // A .flac that is not FLAC at all.
        const QString junkFlac = dir + QStringLiteral("/notreally.flac");
        CHECK(writeFixture(junkFlac, QByteArray("<html><body>404 Not Found</body></html>")));
        CHECK(AudioTags::read(junkFlac).isEmpty());

        // A TRUNCATED mp4: the moov atom declares more bytes than the file holds.
        QByteArray truncated = mp4Atom("ftyp", QByteArray("M4A \x00\x00\x02\x00M4A ", 12));
        appendU32be(truncated, 4096);          // moov, claiming 4 KB...
        truncated.append("moov");
        truncated.append(16, char(0));         // ...of which 16 bytes exist
        const QString truncatedPath = dir + QStringLiteral("/truncated.m4a");
        CHECK(writeFixture(truncatedPath, truncated));
        CHECK(AudioTags::read(truncatedPath).isEmpty());

        // An mp3 of pure garbage: openable, parseable, and carrying nothing.
        const QString garbageMp3 = dir + QStringLiteral("/garbage.mp3");
        CHECK(writeFixture(garbageMp3, QByteArray(2048, '\x7F')));
        CHECK(AudioTags::read(garbageMp3).isEmpty());

        // Zero bytes, a path that does not exist, a directory, and the empty string.
        const QString emptyFile = dir + QStringLiteral("/empty.mp3");
        CHECK(writeFixture(emptyFile, QByteArray()));
        CHECK(AudioTags::read(emptyFile).isEmpty());
        CHECK(AudioTags::read(dir + QStringLiteral("/no-such-file.mp3")).isEmpty());
        CHECK(AudioTags::read(dir).isEmpty());
        CHECK(AudioTags::read(QString()).isEmpty());
    }

    // --- 6. The extension filter the scan will apply before opening anything ------------------------------
    {
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.mp3")));
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.FLAC")));   // case-insensitive
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.m4a")));
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.opus")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/cover.jpg")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/album.nfo")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/movies/film.mkv")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/no-extension")));
    }

    if (g_fails == 0)
        std::printf("MUSICTAGS-OK\n");
    else
        std::printf("MUSICTAGS had %d failure(s)\n", g_fails);
    return g_fails == 0 ? 0 : 1;
}
