// Headless check of the music TAG READER (src/media/AudioTags — issue #74, increment 1): the layer the local
// music library will scan with, browse from, and (issue #141) take its ReplayGain numbers out of.
//
// EVERY FIXTURE IS BUILT HERE, BYTE BY BYTE, from the container specs — an ID3v2.4 tag in front of real MPEG
// audio frames, a FLAC stream header with a Vorbis comment block and two PICTURE blocks, and an MP4 atom tree
// with an ilst full of iTunes items. Nothing binary is committed and nothing is downloaded, for the same
// reason probe_romhack hand-writes its IPS/BPS patches: a checked-in .mp3 is an opaque blob that no reviewer
// can audit and no failure can be read against, and a fixture generated by the code under test proves only
// that the code agrees with itself. Every expected value below is a literal written next to the bytes that
// encode it.
//
// What it pins:
//   1. ID3v2 (.mp3): all eight text fields, the embedded APIC cover, ReplayGain from TXXX frames, and the
//      duration TagLib derives from the frames — with ALBUM ARTIST DIFFERENT FROM ARTIST, the compilation
//      case that #74 names as the classic first bug of a music library.
//   2. Vorbis comments (.flac): unicode values round-tripping, ReplayGain with a 0.00 dB album gain (present
//      and zero, which must not read as absent), a track number with no total, a missing album artist falling
//      back to the artist, the duration from STREAMINFO, and the FRONT cover being chosen out of two
//      pictures — with its mime type sniffed from the bytes because the tag left it blank.
//   3. MP4 atoms (.m4a): the ©-prefixed items, aART as album artist, trkn/disk integer PAIRS, the covr
//      picture, and ReplayGain out of a lowercase iTunes freeform atom (the same value that arrives
//      uppercase from an mp3 — the reader has to answer to both spellings).
//   4. A valid file with NO tag block at all is an EMPTY result, not a half-filled one — and still reports
//      its duration, which is not metadata and must not make the result look non-empty.
//   5. Garbage is REFUSED, not crashed on: a truncated MP4, a .flac that is not FLAC, a zero-byte file, a
//      path that does not exist, and a directory.
//
// Prints MUSICTAGS-OK on success; any failure prints MUSICTAGS-FAIL <cond> (line) and exits non-zero.
//
// Isolation: AppPaths::dataDir() is this process's own scratch dir (issue #42), so every fixture is written
// under it and the tree goes away at exit. Nothing is written beside the exe.
#include "AudioTags.h"
#include "AppPaths.h"

#include <QByteArray>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QString>
#include <cstdio>

static int g_fails = 0;

#define CHECK(cond)                                                                     \
    do {                                                                                \
        if (!(cond)) { std::printf("MUSICTAGS-FAIL %s (%d)\n", #cond, __LINE__); ++g_fails; } \
    } while (0)

// ---------------------------------------------------------------------------------------------------------
// Byte-order helpers. Tag containers disagree about endianness inside the same file — ID3v2 and MP4 are
// big-endian, a Vorbis comment block is little-endian — so each one is spelled out rather than assumed.
// ---------------------------------------------------------------------------------------------------------
static void appendU32be(QByteArray& b, quint32 v)
{
    b.append(char((v >> 24) & 0xFF)); b.append(char((v >> 16) & 0xFF));
    b.append(char((v >> 8) & 0xFF));  b.append(char(v & 0xFF));
}

static void appendU24be(QByteArray& b, quint32 v)
{
    b.append(char((v >> 16) & 0xFF)); b.append(char((v >> 8) & 0xFF)); b.append(char(v & 0xFF));
}

static void appendU16be(QByteArray& b, quint16 v)
{
    b.append(char((v >> 8) & 0xFF)); b.append(char(v & 0xFF));
}

static void appendU32le(QByteArray& b, quint32 v)
{
    b.append(char(v & 0xFF));         b.append(char((v >> 8) & 0xFF));
    b.append(char((v >> 16) & 0xFF)); b.append(char((v >> 24) & 0xFF));
}

// ID3v2 SYNCHSAFE integer: 28 bits carried 7-at-a-time so no size byte can ever look like a frame sync.
static void appendSynchsafe(QByteArray& b, quint32 v)
{
    b.append(char((v >> 21) & 0x7F)); b.append(char((v >> 14) & 0x7F));
    b.append(char((v >> 7) & 0x7F));  b.append(char(v & 0x7F));
}

// ---------------------------------------------------------------------------------------------------------
// ID3v2.4 (.mp3)
// ---------------------------------------------------------------------------------------------------------
// Frame: 4-char id, synchsafe size of the payload, two flag bytes, payload. Text payloads lead with the
// encoding byte 0x03 = UTF-8, which is what makes the unicode cases below legal rather than lucky.
static QByteArray id3Frame(const char* id, const QByteArray& payload)
{
    QByteArray f(id, 4);
    appendSynchsafe(f, quint32(payload.size()));
    f.append(char(0)); f.append(char(0));
    f.append(payload);
    return f;
}

static QByteArray id3TextFrame(const char* id, const QString& text)
{
    QByteArray payload;
    payload.append(char(0x03));
    payload.append(text.toUtf8());
    return id3Frame(id, payload);
}

// TXXX = a user-defined text frame: encoding, NUL-terminated description, value. ReplayGain lives in these.
static QByteArray id3TxxxFrame(const QString& description, const QString& value)
{
    QByteArray payload;
    payload.append(char(0x03));
    payload.append(description.toUtf8());
    payload.append(char(0));
    payload.append(value.toUtf8());
    return id3Frame("TXXX", payload);
}

// APIC: encoding, NUL-terminated Latin-1 mime type, picture-type byte (0x03 = front cover), NUL-terminated
// description, then the image bytes.
static QByteArray id3ApicFrame(const QByteArray& mime, quint8 pictureType, const QByteArray& image)
{
    QByteArray payload;
    payload.append(char(0x03));
    payload.append(mime);
    payload.append(char(0));
    payload.append(char(pictureType));
    payload.append(char(0)); // empty description
    payload.append(image);
    return id3Frame("APIC", payload);
}

static QByteArray id3v2Tag(const QByteArray& frames)
{
    QByteArray tag("ID3", 3);
    tag.append(char(0x04)); tag.append(char(0x00)); // version 2.4.0
    tag.append(char(0x00));                         // no unsynchronisation, no extended header
    appendSynchsafe(tag, quint32(frames.size()));
    tag.append(frames);
    return tag;
}

// N frames of real MPEG-1 Layer III audio: FF FB = sync + MPEG1 + Layer III + no CRC, 0x90 = 128 kbps at
// 44100 Hz with no padding, 0x00 = stereo. Frame length is 144 * 128000 / 44100 = 417 bytes; the payload is
// silence, which TagLib never decodes — it reads the headers.
//
// The DURATION assertion follows from these numbers alone: with no Xing header TagLib treats the stream as
// CBR and computes (stream bytes * 8 / bitrate). 96 frames * 417 = 40032 bytes -> 40032 * 8 / 128 = 2502 ms
// -> 2 seconds. Hand-computed, not read off a run.
static const int kMpegFrameCount  = 96;
static const int kMpegFrameLength = 417;

static QByteArray mpegAudio()
{
    QByteArray frame;
    frame.append(char(0xFF)); frame.append(char(0xFB)); frame.append(char(0x90)); frame.append(char(0x00));
    frame.append(kMpegFrameLength - 4, char(0));

    QByteArray audio;
    for (int i = 0; i < kMpegFrameCount; ++i)
        audio.append(frame);
    return audio;
}

// ---------------------------------------------------------------------------------------------------------
// FLAC (.flac)
// ---------------------------------------------------------------------------------------------------------
// Metadata block header: one byte of (last-block flag | type), then a 24-bit big-endian body length.
static QByteArray flacBlock(quint8 type, const QByteArray& body, bool lastBlock)
{
    QByteArray b;
    b.append(char((lastBlock ? 0x80 : 0x00) | type));
    appendU24be(b, quint32(body.size()));
    b.append(body);
    return b;
}

// STREAMINFO, the one mandatory block. Its bit layout is not byte-aligned: sample rate (20 bits), channels−1
// (3), bits-per-sample−1 (5) and total samples (36) share one 64-bit field, so it is assembled as an integer
// and written big-endian. 44100 Hz * 3 = 132300 samples is where the 3-second duration assertion comes from.
static QByteArray flacStreamInfo(quint32 sampleRate, int channels, int bitsPerSample, quint64 totalSamples)
{
    QByteArray b;
    appendU16be(b, 4096); appendU16be(b, 4096);  // min/max block size
    appendU24be(b, 0);    appendU24be(b, 0);     // min/max frame size, unknown
    const quint64 packed = (quint64(sampleRate) << 44) | (quint64(channels - 1) << 41)
                         | (quint64(bitsPerSample - 1) << 36) | totalSamples;
    for (int shift = 56; shift >= 0; shift -= 8)
        b.append(char((packed >> shift) & 0xFF));
    b.append(16, char(0)); // MD5 of the unencoded audio, all-zero == "not computed"
    return b;
}

// A Vorbis comment block: little-endian length-prefixed vendor string, a count, then that many length-
// prefixed "FIELD=value" strings, all UTF-8.
static QByteArray flacVorbisComment(const QList<QByteArray>& comments)
{
    const QByteArray vendor("probe_musictags");
    QByteArray b;
    appendU32le(b, quint32(vendor.size()));
    b.append(vendor);
    appendU32le(b, quint32(comments.size()));
    for (const QByteArray& c : comments)
    {
        appendU32le(b, quint32(c.size()));
        b.append(c);
    }
    return b;
}

// A PICTURE block: type, length-prefixed mime and description, the four image dimensions nobody validates,
// then the length-prefixed image bytes. All big-endian, unlike the comment block two functions up.
static QByteArray flacPicture(quint32 pictureType, const QByteArray& mime, const QByteArray& image)
{
    QByteArray b;
    appendU32be(b, pictureType);
    appendU32be(b, quint32(mime.size()));  b.append(mime);
    appendU32be(b, 0);                     // empty description
    appendU32be(b, 300); appendU32be(b, 300); appendU32be(b, 24); appendU32be(b, 0);
    appendU32be(b, quint32(image.size())); b.append(image);
    return b;
}

// ---------------------------------------------------------------------------------------------------------
// MP4 (.m4a)
// ---------------------------------------------------------------------------------------------------------
static QByteArray mp4Atom(const QByteArray& name, const QByteArray& body)
{
    QByteArray b;
    appendU32be(b, quint32(8 + body.size()));
    b.append(name);
    b.append(body);
    return b;
}

// The iTunes item names begin with the copyright sign (0xA9) — written as a byte rather than in a string
// literal, where the following letter would be swallowed by the \x escape ("\xA9alb" is one bad character).
static QByteArray itunesName(const char* threeLetters)
{
    QByteArray n(1, char(0xA9));
    n.append(threeLetters, 3);
    return n;
}

// The `data` atom inside an item: a version/flags word whose low byte is the VALUE TYPE (1 = UTF-8 text,
// 0 = implicit, 13 = JPEG, 14 = PNG), a reserved locale word, then the value.
static QByteArray mp4DataAtom(quint32 type, const QByteArray& payload)
{
    QByteArray body;
    appendU32be(body, type);
    appendU32be(body, 0);
    body.append(payload);
    return mp4Atom("data", body);
}

static QByteArray mp4TextItem(const QByteArray& name, const QString& text)
{
    return mp4Atom(name, mp4DataAtom(1, text.toUtf8()));
}

// trkn / disk store BOTH numbers in one implicit-typed value: two reserved bytes, the number, the total.
static QByteArray mp4PairItem(const QByteArray& name, quint16 number, quint16 total)
{
    QByteArray payload;
    appendU16be(payload, 0);
    appendU16be(payload, number);
    appendU16be(payload, total);
    appendU16be(payload, 0);
    return mp4Atom(name, mp4DataAtom(0, payload));
}

// A freeform ("----") item: a `mean` atom naming the vendor, a `name` atom naming the key, then the value.
// This is how everything outside the fixed iTunes vocabulary — ReplayGain included — is stored in an m4a.
static QByteArray mp4FreeformItem(const QByteArray& key, const QString& value)
{
    QByteArray meanBody; appendU32be(meanBody, 0); meanBody.append("com.apple.iTunes");
    QByteArray nameBody; appendU32be(nameBody, 0); nameBody.append(key);
    QByteArray body = mp4Atom("mean", meanBody);
    body.append(mp4Atom("name", nameBody));
    body.append(mp4DataAtom(1, value.toUtf8()));
    return mp4Atom("----", body);
}

// ---------------------------------------------------------------------------------------------------------
static bool writeFixture(const QString& path, const QByteArray& bytes)
{
    QDir().mkpath(QFileInfo(path).absolutePath());
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate))
        return false;
    return f.write(bytes) == bytes.size();
}

// Plausible image headers — enough for a mime sniff to be a real test, and never decoded by anything here.
static QByteArray jpegBytes()
{
    QByteArray b("\xFF\xD8\xFF\xE0", 4);
    b.append("\x00\x10JFIF", 6);
    b.append(64, 'J');
    b.append("\xFF\xD9", 2);
    return b;
}

static QByteArray pngBytes()
{
    QByteArray b("\x89PNG\r\n\x1A\n", 8);
    b.append(64, 'P');
    return b;
}

int main(int argc, char** argv)
{
    QCoreApplication app(argc, argv);

    const QString dir = AppPaths::dataDir() + QStringLiteral("/musictags");
    QDir().mkpath(dir);

    const QByteArray jpeg = jpegBytes();
    const QByteArray png  = pngBytes();

    // --- 1. ID3v2.4 in an mp3: every field, the cover, ReplayGain, duration — and a COMPILATION ------------
    // Album artist deliberately differs from artist. A browse that groups on `artist` would split this album
    // into one album per track, which is the failure #74 calls out; the reader has to keep the two apart.
    {
        QByteArray frames;
        frames.append(id3TextFrame("TIT2", QStringLiteral("Windowlicker")));
        frames.append(id3TextFrame("TPE1", QStringLiteral("Aphex Twin")));       // track artist
        frames.append(id3TextFrame("TPE2", QStringLiteral("Various Artists")));  // ALBUM artist
        frames.append(id3TextFrame("TALB", QStringLiteral("Warp Sampler")));
        frames.append(id3TextFrame("TRCK", QStringLiteral("3/12")));
        frames.append(id3TextFrame("TPOS", QStringLiteral("1/2")));
        frames.append(id3TextFrame("TDRC", QStringLiteral("1999-03-22")));
        frames.append(id3TextFrame("TCON", QStringLiteral("Electronic")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_TRACK_GAIN"), QStringLiteral("-7.15 dB")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_TRACK_PEAK"), QStringLiteral("0.988525")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_ALBUM_GAIN"), QStringLiteral("-6.02 dB")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_ALBUM_PEAK"), QStringLiteral("1.014000")));
        frames.append(id3ApicFrame("image/jpeg", 0x03, jpeg));

        const QString path = dir + QStringLiteral("/compilation.mp3");
        CHECK(writeFixture(path, id3v2Tag(frames) + mpegAudio()));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == QStringLiteral("Windowlicker"));
        CHECK(t.artist == QStringLiteral("Aphex Twin"));
        CHECK(t.albumArtist == QStringLiteral("Various Artists"));
        CHECK(t.albumArtist != t.artist);                                  // the compilation distinction itself
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Various Artists"));
        CHECK(t.album == QStringLiteral("Warp Sampler"));
        CHECK(t.genre == QStringLiteral("Electronic"));
        CHECK(t.track == 3);
        CHECK(t.trackTotal == 12);
        CHECK(t.disc == 1);
        CHECK(t.discTotal == 2);
        CHECK(t.year == 1999);                                             // out of "1999-03-22"
        CHECK(t.durationSec == 2);                                         // 40032 bytes * 8 / 128 kbps
        CHECK(t.cover.data == jpeg);
        CHECK(t.cover.mimeType == QStringLiteral("image/jpeg"));
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - (-7.15)) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 0.988525) < 1e-9);
        CHECK(t.albumGain.present && qAbs(t.albumGain.value - (-6.02)) < 1e-9);
        CHECK(t.albumPeak.present && qAbs(t.albumPeak.value - 1.014) < 1e-9);
    }

    // --- 2. Vorbis comments in a flac: unicode, no album artist, 0 dB album gain, two pictures -------------
    // The title/artist are Japanese and the album is accented Latin: a tag reader that goes through the
    // platform code page instead of UTF-8 mangles both, and a library indexed off mangled names cannot be
    // searched. ALBUMARTIST is absent on purpose — the fallback to the track artist is the tested behaviour.
    {
        const QString uTitle  = QString::fromUtf8("\xE3\x83\xAD\xE3\x83\x9E\xE3\x83\xB3\xE3\x82\xB9");   // ロマンス
        const QString uArtist = QString::fromUtf8("\xE5\xBA\x83\xE7\x80\xAC\xE9\xA6\x99\xE7\xBE\x8E");   // 広瀬香美
        const QString uAlbum  = QString::fromUtf8("Caf\xC3\xA9 del M\xC3\xA1r");                          // Café del Már

        QList<QByteArray> comments;
        comments << QByteArray("TITLE=") + uTitle.toUtf8();
        comments << QByteArray("ARTIST=") + uArtist.toUtf8();
        comments << QByteArray("ALBUM=") + uAlbum.toUtf8();
        comments << QByteArray("GENRE=J-Pop");
        comments << QByteArray("DATE=1993");
        comments << QByteArray("TRACKNUMBER=5");                        // no total: trackTotal stays 0
        comments << QByteArray("REPLAYGAIN_TRACK_GAIN=+3.20 dB");
        comments << QByteArray("REPLAYGAIN_TRACK_PEAK=0.500000");
        comments << QByteArray("REPLAYGAIN_ALBUM_GAIN=0.00 dB");        // present AND zero
        comments << QByteArray("REPLAYGAIN_ALBUM_PEAK=0.750000");

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), false)); // 132300/44100 = 3 seconds
        flac.append(flacBlock(4, flacVorbisComment(comments), false));
        flac.append(flacBlock(6, flacPicture(4, "image/jpeg", jpeg), false));   // 4 = BACK cover, first
        flac.append(flacBlock(6, flacPicture(3, QByteArray(), png), true));     // 3 = FRONT cover, blank mime

        const QString path = dir + QStringLiteral("/unicode.flac");
        CHECK(writeFixture(path, flac));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == uTitle);
        CHECK(t.artist == uArtist);
        CHECK(t.album == uAlbum);
        CHECK(t.genre == QStringLiteral("J-Pop"));
        CHECK(t.albumArtist.isEmpty());                    // not tagged -> stays empty, never guessed
        CHECK(t.effectiveAlbumArtist() == uArtist);        // ...and the grouping key falls back to the artist
        CHECK(t.track == 5);
        CHECK(t.trackTotal == 0);                          // "5" carries no total
        CHECK(t.disc == 0);
        CHECK(t.year == 1993);
        CHECK(t.durationSec == 3);                         // 132300 samples / 44100 Hz
        CHECK(t.cover.data == png);                        // the FRONT cover, not the back one that came first
        CHECK(t.cover.mimeType == QStringLiteral("image/png")); // sniffed: the PICTURE block's mime was blank
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - 3.20) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 0.5) < 1e-9);
        CHECK(t.albumGain.present && qAbs(t.albumGain.value - 0.0) < 1e-9); // 0 dB is a VALUE, not an absence
        CHECK(t.albumPeak.present && qAbs(t.albumPeak.value - 0.75) < 1e-9);
    }

    // --- 3. MP4 atoms in an m4a: aART, integer pairs, covr, and a LOWERCASE freeform ReplayGain ------------
    // iTunes writes its freeform keys lowercase while ID3v2 TXXX descriptions arrive uppercased, so the same
    // ReplayGain tag has two spellings across two containers and the reader must answer to both.
    {
        QByteArray ilst;
        ilst.append(mp4TextItem(itunesName("nam"), QStringLiteral("Bohemian Rhapsody")));
        ilst.append(mp4TextItem(itunesName("ART"), QStringLiteral("Queen")));
        ilst.append(mp4TextItem("aART", QStringLiteral("Freddie & Friends")));  // album artist != artist again
        ilst.append(mp4TextItem(itunesName("alb"), QStringLiteral("A Night at the Opera")));
        ilst.append(mp4TextItem(itunesName("gen"), QStringLiteral("Rock")));
        ilst.append(mp4TextItem(itunesName("day"), QStringLiteral("1975")));
        ilst.append(mp4PairItem("trkn", 11, 12));
        ilst.append(mp4PairItem("disk", 1, 1));
        ilst.append(mp4Atom("covr", mp4DataAtom(14, png)));                     // 14 = PNG
        ilst.append(mp4FreeformItem("replaygain_track_gain", QStringLiteral("-9.35 dB")));
        ilst.append(mp4FreeformItem("replaygain_track_peak", QStringLiteral("1.030000")));

        // meta is a "full atom": four bytes of version/flags before its children. hdlr's contents are never
        // read here, but iTunes writes one and TagLib's own meta-vs-full-atom detection looks at what follows.
        QByteArray hdlrBody;
        appendU32be(hdlrBody, 0); appendU32be(hdlrBody, 0);
        hdlrBody.append("mdirappl");
        hdlrBody.append(12, char(0));

        QByteArray metaBody;
        appendU32be(metaBody, 0);
        metaBody.append(mp4Atom("hdlr", hdlrBody));
        metaBody.append(mp4Atom("ilst", ilst));

        QByteArray ftypBody("M4A ", 4);
        appendU32be(ftypBody, 512);
        ftypBody.append("M4A mp42isom");

        // No trak/mdhd: this fixture is a tag block, not an encoded song, so there is no timescale to read a
        // duration from. durationSec is asserted to be 0 BECAUSE of that — the reader must report "unknown"
        // rather than inventing a length, and the two containers above already pin a real duration.
        QByteArray m4a = mp4Atom("ftyp", ftypBody);
        m4a.append(mp4Atom("moov", mp4Atom("udta", mp4Atom("meta", metaBody))));

        const QString path = dir + QStringLiteral("/opera.m4a");
        CHECK(writeFixture(path, m4a));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == QStringLiteral("Bohemian Rhapsody"));
        CHECK(t.artist == QStringLiteral("Queen"));
        CHECK(t.albumArtist == QStringLiteral("Freddie & Friends"));
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Freddie & Friends"));
        CHECK(t.album == QStringLiteral("A Night at the Opera"));
        CHECK(t.genre == QStringLiteral("Rock"));
        CHECK(t.track == 11);
        CHECK(t.trackTotal == 12);
        CHECK(t.disc == 1);
        CHECK(t.discTotal == 1);
        CHECK(t.year == 1975);
        CHECK(t.durationSec == 0);                          // no audio track in the fixture; see above
        CHECK(t.cover.data == png);
        CHECK(t.cover.mimeType == QStringLiteral("image/png"));
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - (-9.35)) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 1.03) < 1e-9);
        CHECK(!t.albumGain.present);                        // not tagged -> absent, not 0
        CHECK(!t.albumPeak.present);
    }

    // --- 4. A valid file with NO tags is an EMPTY result --------------------------------------------------
    // Both halves matter: nothing is invented for the fields, and the duration that IS readable does not make
    // the result look tagged. The scan uses isEmpty() to decide a file needs its filename fallback.
    {
        const QString mp3 = dir + QStringLiteral("/untagged.mp3");
        CHECK(writeFixture(mp3, mpegAudio()));
        const AudioTags::Tags t = AudioTags::read(mp3);
        CHECK(t.isEmpty());
        CHECK(t.title.isEmpty() && t.artist.isEmpty() && t.albumArtist.isEmpty() && t.album.isEmpty());
        CHECK(t.track == 0 && t.disc == 0 && t.year == 0);
        CHECK(t.cover.isNull());
        CHECK(!t.trackGain.present && !t.albumGain.present);
        CHECK(t.durationSec == 2);          // readable, and still not metadata

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), true));
        const QString flacPath = dir + QStringLiteral("/untagged.flac");
        CHECK(writeFixture(flacPath, flac));
        const AudioTags::Tags f = AudioTags::read(flacPath);
        CHECK(f.isEmpty());
        CHECK(f.durationSec == 3);
    }

    // --- 5. Broken input is refused, never crashed on -----------------------------------------------------
    // A library scan walks whatever is on the disk: half-finished downloads, files renamed by hand, an error
    // page saved with an .mp3 on the end. Every one of these has to come back empty and come back at all.
    {
        // A .flac that is not FLAC at all.
        const QString junkFlac = dir + QStringLiteral("/notreally.flac");
        CHECK(writeFixture(junkFlac, QByteArray("<html><body>404 Not Found</body></html>")));
        CHECK(AudioTags::read(junkFlac).isEmpty());

        // A TRUNCATED mp4: the moov atom declares more bytes than the file holds.
        QByteArray truncated = mp4Atom("ftyp", QByteArray("M4A \x00\x00\x02\x00M4A ", 12));
        appendU32be(truncated, 4096);          // moov, claiming 4 KB...
        truncated.append("moov");
        truncated.append(16, char(0));         // ...of which 16 bytes exist
        const QString truncatedPath = dir + QStringLiteral("/truncated.m4a");
        CHECK(writeFixture(truncatedPath, truncated));
        CHECK(AudioTags::read(truncatedPath).isEmpty());

        // An mp3 of pure garbage: openable, parseable, and carrying nothing.
        const QString garbageMp3 = dir + QStringLiteral("/garbage.mp3");
        CHECK(writeFixture(garbageMp3, QByteArray(2048, '\x7F')));
        CHECK(AudioTags::read(garbageMp3).isEmpty());

        // Zero bytes, a path that does not exist, a directory, and the empty string.
        const QString emptyFile = dir + QStringLiteral("/empty.mp3");
        CHECK(writeFixture(emptyFile, QByteArray()));
        CHECK(AudioTags::read(emptyFile).isEmpty());
        CHECK(AudioTags::read(dir + QStringLiteral("/no-such-file.mp3")).isEmpty());
        CHECK(AudioTags::read(dir).isEmpty());
        CHECK(AudioTags::read(QString()).isEmpty());
    }

    // --- 6. The extension filter the scan will apply before opening anything ------------------------------
    {
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.mp3")));
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.FLAC")));   // case-insensitive
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.m4a")));
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.opus")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/cover.jpg")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/album.nfo")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/movies/film.mkv")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/no-extension")));
    }

    if (g_fails == 0)
        std::printf("MUSICTAGS-OK\n");
    else
        std::printf("MUSICTAGS had %d failure(s)\n", g_fails);
    return g_fails == 0 ? 0 : 1;
}
