// Headless check of the music TAG READER (src/media/AudioTags — issue #74, increment 1): the layer the local
// music library will scan with, browse from, and (issue #141) take its ReplayGain numbers out of.
//
// EVERY FIXTURE IS BUILT BYTE BY BYTE from the container specs — an ID3v2.4 tag in front of real MPEG audio
// frames, a FLAC stream header with a Vorbis comment block and two PICTURE blocks, and an MP4 atom tree with
// an ilst full of iTunes items. Nothing binary is committed and nothing is downloaded, for the same reason
// probe_romhack hand-writes its IPS/BPS patches: a checked-in .mp3 is an opaque blob that no reviewer can
// audit and no failure can be read against, and a fixture generated by the code under test proves only that
// the code agrees with itself. Every expected value below is a literal written next to the bytes that encode
// it. The builders themselves moved to tools/MusicFixtures.h when probe_musiclibrary (issue #74, increment 2)
// needed the same bytes — one builder, two probes, so a scan probe can never disagree with this one about
// what a well-formed file looks like.
//
// What it pins:
//   1. ID3v2 (.mp3): all eight text fields, the embedded APIC cover, ReplayGain from TXXX frames, and the
//      duration TagLib derives from the frames — with ALBUM ARTIST DIFFERENT FROM ARTIST, the compilation
//      case that #74 names as the classic first bug of a music library.
//   2. Vorbis comments (.flac): unicode values round-tripping, ReplayGain with a 0.00 dB album gain (present
//      and zero, which must not read as absent), a track number with no total, a missing album artist falling
//      back to the artist, the duration from STREAMINFO, and the FRONT cover being chosen out of two
//      pictures — with its mime type sniffed from the bytes because the tag left it blank.
//   3. MP4 atoms (.m4a): the ©-prefixed items, aART as album artist, trkn/disk integer PAIRS, the covr
//      picture, and ReplayGain out of a lowercase iTunes freeform atom (the same value that arrives
//      uppercase from an mp3 — the reader has to answer to both spellings).
//   4. A valid file with NO tag block at all is an EMPTY result, not a half-filled one — and still reports
//      its duration, which is not metadata and must not make the result look non-empty.
//   5. Garbage is REFUSED, not crashed on: a truncated MP4, a .flac that is not FLAC, a zero-byte file, a
//      path that does not exist, and a directory.
//   6. MULTI-VALUE ARTIST AND GENRE (issue #196): a repeated Vorbis field and a NUL-separated ID3v2.4 frame
//      both yield several values with NO separator list configured, an ID3v2.3 single string yields several
//      only when one is; ALBUM ARTIST is never split; "AC/DC" survives the default list, and a STRUCTURED
//      "AC/DC" survives even a list containing "/".
//   7. splitTagValues on its own: punctuation matches anywhere, a separator with a letter in it needs
//      whitespace on both sides, duplicates collapse, and a degenerate value is never deleted.
//
// Prints MUSICTAGS-OK on success; any failure prints MUSICTAGS-FAIL <cond> (line) and exits non-zero.
//
// Isolation: AppPaths::dataDir() is this process's own scratch dir (issue #42), so every fixture is written
// under it and the tree goes away at exit. Nothing is written beside the exe.
#include "AudioTags.h"
#include "AppPaths.h"
#include "MusicFixtures.h"

#include <QByteArray>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QString>
#include <cstdio>

static int g_fails = 0;

#define CHECK(cond)                                                                     \
    do {                                                                                \
        if (!(cond)) { std::printf("MUSICTAGS-FAIL %s (%d)\n", #cond, __LINE__); ++g_fails; } \
    } while (0)

// The fixture builders (ID3v2 / FLAC / MP4 byte assembly, the image blobs and writeFixture) live in
// MusicFixtures.h so probe_musiclibrary builds its scan fixtures from the SAME bytes this probe pins
// the reader against. See that header for why they are hand-written rather than committed.

int main(int argc, char** argv)
{
    QCoreApplication app(argc, argv);

    const QString dir = AppPaths::dataDir() + QStringLiteral("/musictags");
    QDir().mkpath(dir);

    const QByteArray jpeg = jpegBytes();
    const QByteArray png  = pngBytes();

    // --- 1. ID3v2.4 in an mp3: every field, the cover, ReplayGain, duration — and a COMPILATION ------------
    // Album artist deliberately differs from artist. A browse that groups on `artist` would split this album
    // into one album per track, which is the failure #74 calls out; the reader has to keep the two apart.
    {
        QByteArray frames;
        frames.append(id3TextFrame("TIT2", QStringLiteral("Windowlicker")));
        frames.append(id3TextFrame("TPE1", QStringLiteral("Aphex Twin")));       // track artist
        frames.append(id3TextFrame("TPE2", QStringLiteral("Various Artists")));  // ALBUM artist
        frames.append(id3TextFrame("TALB", QStringLiteral("Warp Sampler")));
        frames.append(id3TextFrame("TRCK", QStringLiteral("3/12")));
        frames.append(id3TextFrame("TPOS", QStringLiteral("1/2")));
        frames.append(id3TextFrame("TDRC", QStringLiteral("1999-03-22")));
        frames.append(id3TextFrame("TCON", QStringLiteral("Electronic")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_TRACK_GAIN"), QStringLiteral("-7.15 dB")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_TRACK_PEAK"), QStringLiteral("0.988525")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_ALBUM_GAIN"), QStringLiteral("-6.02 dB")));
        frames.append(id3TxxxFrame(QStringLiteral("REPLAYGAIN_ALBUM_PEAK"), QStringLiteral("1.014000")));
        frames.append(id3ApicFrame("image/jpeg", 0x03, jpeg));

        const QString path = dir + QStringLiteral("/compilation.mp3");
        CHECK(writeFixture(path, mp3File(frames)));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == QStringLiteral("Windowlicker"));
        CHECK(t.artist == QStringLiteral("Aphex Twin"));
        CHECK(t.albumArtist == QStringLiteral("Various Artists"));
        CHECK(t.albumArtist != t.artist);                                  // the compilation distinction itself
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Various Artists"));
        CHECK(t.album == QStringLiteral("Warp Sampler"));
        CHECK(t.genre == QStringLiteral("Electronic"));
        CHECK(t.track == 3);
        CHECK(t.trackTotal == 12);
        CHECK(t.disc == 1);
        CHECK(t.discTotal == 2);
        CHECK(t.year == 1999);                                             // out of "1999-03-22"
        CHECK(t.durationSec == 2);                                         // 40032 bytes * 8 / 128 kbps
        CHECK(t.cover.data == jpeg);
        CHECK(t.cover.mimeType == QStringLiteral("image/jpeg"));
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - (-7.15)) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 0.988525) < 1e-9);
        CHECK(t.albumGain.present && qAbs(t.albumGain.value - (-6.02)) < 1e-9);
        CHECK(t.albumPeak.present && qAbs(t.albumPeak.value - 1.014) < 1e-9);
    }

    // --- 2. Vorbis comments in a flac: unicode, no album artist, 0 dB album gain, two pictures -------------
    // The title/artist are Japanese and the album is accented Latin: a tag reader that goes through the
    // platform code page instead of UTF-8 mangles both, and a library indexed off mangled names cannot be
    // searched. ALBUMARTIST is absent on purpose — the fallback to the track artist is the tested behaviour.
    {
        const QString uTitle  = QString::fromUtf8("\xE3\x83\xAD\xE3\x83\x9E\xE3\x83\xB3\xE3\x82\xB9");   // ロマンス
        const QString uArtist = QString::fromUtf8("\xE5\xBA\x83\xE7\x80\xAC\xE9\xA6\x99\xE7\xBE\x8E");   // 広瀬香美
        const QString uAlbum  = QString::fromUtf8("Caf\xC3\xA9 del M\xC3\xA1r");                          // Café del Már

        QList<QByteArray> comments;
        comments << QByteArray("TITLE=") + uTitle.toUtf8();
        comments << QByteArray("ARTIST=") + uArtist.toUtf8();
        comments << QByteArray("ALBUM=") + uAlbum.toUtf8();
        comments << QByteArray("GENRE=J-Pop");
        comments << QByteArray("DATE=1993");
        comments << QByteArray("TRACKNUMBER=5");                        // no total: trackTotal stays 0
        comments << QByteArray("REPLAYGAIN_TRACK_GAIN=+3.20 dB");
        comments << QByteArray("REPLAYGAIN_TRACK_PEAK=0.500000");
        comments << QByteArray("REPLAYGAIN_ALBUM_GAIN=0.00 dB");        // present AND zero
        comments << QByteArray("REPLAYGAIN_ALBUM_PEAK=0.750000");

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), false)); // 132300/44100 = 3 seconds
        flac.append(flacBlock(4, flacVorbisComment(comments), false));
        flac.append(flacBlock(6, flacPicture(4, "image/jpeg", jpeg), false));   // 4 = BACK cover, first
        flac.append(flacBlock(6, flacPicture(3, QByteArray(), png), true));     // 3 = FRONT cover, blank mime

        const QString path = dir + QStringLiteral("/unicode.flac");
        CHECK(writeFixture(path, flac));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == uTitle);
        CHECK(t.artist == uArtist);
        CHECK(t.album == uAlbum);
        CHECK(t.genre == QStringLiteral("J-Pop"));
        CHECK(t.albumArtist.isEmpty());                    // not tagged -> stays empty, never guessed
        CHECK(t.effectiveAlbumArtist() == uArtist);        // ...and the grouping key falls back to the artist
        CHECK(t.track == 5);
        CHECK(t.trackTotal == 0);                          // "5" carries no total
        CHECK(t.disc == 0);
        CHECK(t.year == 1993);
        CHECK(t.durationSec == 3);                         // 132300 samples / 44100 Hz
        CHECK(t.cover.data == png);                        // the FRONT cover, not the back one that came first
        CHECK(t.cover.mimeType == QStringLiteral("image/png")); // sniffed: the PICTURE block's mime was blank
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - 3.20) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 0.5) < 1e-9);
        CHECK(t.albumGain.present && qAbs(t.albumGain.value - 0.0) < 1e-9); // 0 dB is a VALUE, not an absence
        CHECK(t.albumPeak.present && qAbs(t.albumPeak.value - 0.75) < 1e-9);
    }

    // --- 3. MP4 atoms in an m4a: aART, integer pairs, covr, and a LOWERCASE freeform ReplayGain ------------
    // iTunes writes its freeform keys lowercase while ID3v2 TXXX descriptions arrive uppercased, so the same
    // ReplayGain tag has two spellings across two containers and the reader must answer to both.
    {
        QByteArray ilst;
        ilst.append(mp4TextItem(itunesName("nam"), QStringLiteral("Bohemian Rhapsody")));
        ilst.append(mp4TextItem(itunesName("ART"), QStringLiteral("Queen")));
        ilst.append(mp4TextItem("aART", QStringLiteral("Freddie & Friends")));  // album artist != artist again
        ilst.append(mp4TextItem(itunesName("alb"), QStringLiteral("A Night at the Opera")));
        ilst.append(mp4TextItem(itunesName("gen"), QStringLiteral("Rock")));
        ilst.append(mp4TextItem(itunesName("day"), QStringLiteral("1975")));
        ilst.append(mp4PairItem("trkn", 11, 12));
        ilst.append(mp4PairItem("disk", 1, 1));
        ilst.append(mp4Atom("covr", mp4DataAtom(14, png)));                     // 14 = PNG
        ilst.append(mp4FreeformItem("replaygain_track_gain", QStringLiteral("-9.35 dB")));
        ilst.append(mp4FreeformItem("replaygain_track_peak", QStringLiteral("1.030000")));

        // m4aFile() wraps the ilst in ftyp + moov/udta/meta (MusicFixtures.h explains the full-atom layout and
        // the hdlr TagLib's detection looks at). It writes NO trak/mdhd, so this fixture is a tag block rather
        // than an encoded song and durationSec is asserted to be 0 BECAUSE of that — the reader must report
        // "unknown" rather than invent a length, and the two containers above already pin a real duration.
        const QString path = dir + QStringLiteral("/opera.m4a");
        CHECK(writeFixture(path, m4aFile(ilst)));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(!t.isEmpty());
        CHECK(t.title == QStringLiteral("Bohemian Rhapsody"));
        CHECK(t.artist == QStringLiteral("Queen"));
        CHECK(t.albumArtist == QStringLiteral("Freddie & Friends"));
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Freddie & Friends"));
        CHECK(t.album == QStringLiteral("A Night at the Opera"));
        CHECK(t.genre == QStringLiteral("Rock"));
        CHECK(t.track == 11);
        CHECK(t.trackTotal == 12);
        CHECK(t.disc == 1);
        CHECK(t.discTotal == 1);
        CHECK(t.year == 1975);
        CHECK(t.durationSec == 0);                          // no audio track in the fixture; see above
        CHECK(t.cover.data == png);
        CHECK(t.cover.mimeType == QStringLiteral("image/png"));
        CHECK(t.trackGain.present && qAbs(t.trackGain.value - (-9.35)) < 1e-9);
        CHECK(t.trackPeak.present && qAbs(t.trackPeak.value - 1.03) < 1e-9);
        CHECK(!t.albumGain.present);                        // not tagged -> absent, not 0
        CHECK(!t.albumPeak.present);
    }

    // --- 4. A valid file with NO tags is an EMPTY result --------------------------------------------------
    // Both halves matter: nothing is invented for the fields, and the duration that IS readable does not make
    // the result look tagged. The scan uses isEmpty() to decide a file needs its filename fallback.
    {
        const QString mp3 = dir + QStringLiteral("/untagged.mp3");
        CHECK(writeFixture(mp3, mpegAudio()));
        const AudioTags::Tags t = AudioTags::read(mp3);
        CHECK(t.isEmpty());
        CHECK(t.title.isEmpty() && t.artist.isEmpty() && t.albumArtist.isEmpty() && t.album.isEmpty());
        CHECK(t.track == 0 && t.disc == 0 && t.year == 0);
        CHECK(t.cover.isNull());
        CHECK(!t.trackGain.present && !t.albumGain.present);
        CHECK(t.durationSec == 2);          // readable, and still not metadata

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), true));
        const QString flacPath = dir + QStringLiteral("/untagged.flac");
        CHECK(writeFixture(flacPath, flac));
        const AudioTags::Tags f = AudioTags::read(flacPath);
        CHECK(f.isEmpty());
        CHECK(f.durationSec == 3);
    }

    // --- 5. Broken input is refused, never crashed on -----------------------------------------------------
    // A library scan walks whatever is on the disk: half-finished downloads, files renamed by hand, an error
    // page saved with an .mp3 on the end. Every one of these has to come back empty and come back at all.
    {
        // A .flac that is not FLAC at all.
        const QString junkFlac = dir + QStringLiteral("/notreally.flac");
        CHECK(writeFixture(junkFlac, QByteArray("<html><body>404 Not Found</body></html>")));
        CHECK(AudioTags::read(junkFlac).isEmpty());

        // A TRUNCATED mp4: the moov atom declares more bytes than the file holds.
        QByteArray truncated = mp4Atom("ftyp", QByteArray("M4A \x00\x00\x02\x00M4A ", 12));
        appendU32be(truncated, 4096);          // moov, claiming 4 KB...
        truncated.append("moov");
        truncated.append(16, char(0));         // ...of which 16 bytes exist
        const QString truncatedPath = dir + QStringLiteral("/truncated.m4a");
        CHECK(writeFixture(truncatedPath, truncated));
        CHECK(AudioTags::read(truncatedPath).isEmpty());

        // An mp3 of pure garbage: openable, parseable, and carrying nothing.
        const QString garbageMp3 = dir + QStringLiteral("/garbage.mp3");
        CHECK(writeFixture(garbageMp3, QByteArray(2048, '\x7F')));
        CHECK(AudioTags::read(garbageMp3).isEmpty());

        // Zero bytes, a path that does not exist, a directory, and the empty string.
        const QString emptyFile = dir + QStringLiteral("/empty.mp3");
        CHECK(writeFixture(emptyFile, QByteArray()));
        CHECK(AudioTags::read(emptyFile).isEmpty());
        CHECK(AudioTags::read(dir + QStringLiteral("/no-such-file.mp3")).isEmpty());
        CHECK(AudioTags::read(dir).isEmpty());
        CHECK(AudioTags::read(QString()).isEmpty());
    }

    // --- 6. MULTI-VALUE ARTIST AND GENRE (issue #196, part 1) --------------------------------------------
    // The part with judgement in it. Two things have to be true at once: a file that says several artists
    // must yield several artists, and a file that says ONE artist whose name merely LOOKS like a list must
    // not be shredded. The second failure is the dangerous one — it is invisible until somebody goes looking
    // for a band that has quietly become two — so the default separator list is one character and every case
    // below that could shred a name is asserted intact.
    {
        // 6a. A VORBIS COMMENT BLOCK REPEATS THE FIELD. Three ARTIST comments and two GENREs, and NO ad-hoc
        //     separators passed at all: the container already answered, and structured values must arrive
        //     without any splitting policy being configured. This is the shape FLAC/Ogg taggers write.
        QList<QByteArray> comments;
        comments << QByteArray("TITLE=Interstate Love Song");
        comments << QByteArray("ARTIST=Stone Temple Pilots");
        comments << QByteArray("ARTIST=Scott Weiland");
        comments << QByteArray("ARTIST=Dean DeLeo");
        comments << QByteArray("ALBUM=Purple");
        comments << QByteArray("GENRE=Rock");
        comments << QByteArray("GENRE=Grunge");

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), false));
        flac.append(flacBlock(4, flacVorbisComment(comments), true));

        const QString path = dir + QStringLiteral("/repeated.flac");
        CHECK(writeFixture(path, flac));

        const AudioTags::Tags t = AudioTags::read(path);          // no separators: structured only
        CHECK(t.artists.size() == 3);
        CHECK(t.artists.value(0) == QStringLiteral("Stone Temple Pilots"));
        CHECK(t.artists.value(1) == QStringLiteral("Scott Weiland"));
        CHECK(t.artists.value(2) == QStringLiteral("Dean DeLeo"));
        // The display string is the list joined with the app's own default separator, so what a person reads
        // is a string this reader would parse straight back into the same three names.
        CHECK(t.artist == QStringLiteral("Stone Temple Pilots; Scott Weiland; Dean DeLeo"));
        CHECK(t.genres.size() == 2);
        CHECK(t.genres.value(0) == QStringLiteral("Rock"));
        CHECK(t.genres.value(1) == QStringLiteral("Grunge"));
        CHECK(t.genre == QStringLiteral("Rock; Grunge"));
        // No ALBUMARTIST, so the album groups under the FIRST artist — not under the whole credit, which is
        // the artist entry nobody could reach that #196 opens with.
        CHECK(t.albumArtist.isEmpty());
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Stone Temple Pilots"));
    }
    {
        // 6b. ID3v2.4 SEPARATES VALUES WITH A NUL inside ONE frame. Same requirement, different encoding —
        //     and again with no separators configured.
        QByteArray frames;
        frames.append(id3TextFrame("TIT2", QStringLiteral("Under Pressure")));
        frames.append(id3MultiTextFrame("TPE1", { QStringLiteral("Queen"), QStringLiteral("David Bowie") }));
        frames.append(id3MultiTextFrame("TCON", { QStringLiteral("Rock"), QStringLiteral("Pop") }));
        frames.append(id3TextFrame("TALB", QStringLiteral("Hot Space")));

        const QString path = dir + QStringLiteral("/nulsep.mp3");
        CHECK(writeFixture(path, mp3File(frames)));

        const AudioTags::Tags t = AudioTags::read(path);
        CHECK(t.artists.size() == 2);
        CHECK(t.artists.value(0) == QStringLiteral("Queen"));
        CHECK(t.artists.value(1) == QStringLiteral("David Bowie"));
        CHECK(t.artist == QStringLiteral("Queen; David Bowie"));
        CHECK(t.genres.size() == 2);
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Queen"));
    }
    {
        // 6c. AD-HOC SEPARATORS, the ID3v2.3 case: one string, one tagger's guess at how to flatten a list.
        //     Split ONLY when the caller asked for it — the reader itself holds no policy, so the same file
        //     read with no separator list is one artist, which is what a one-off read (cover art, the
        //     now-playing panel) must not have quietly reinterpreted underneath it.
        QByteArray frames;
        frames.append(id3TextFrame("TIT2", QStringLiteral("Numb / Encore")));
        frames.append(id3TextFrame("TPE1", QStringLiteral("Linkin Park;Jay-Z")));   // no space after the ';'
        frames.append(id3TextFrame("TPE2", QStringLiteral("Linkin Park; Jay-Z")));  // ALBUM artist, same shape
        frames.append(id3TextFrame("TCON", QStringLiteral("Rap; Rock")));
        frames.append(id3TextFrame("TALB", QStringLiteral("Collision Course")));

        const QString path = dir + QStringLiteral("/adhoc.mp3");
        CHECK(writeFixture(path, mp3File(frames)));

        const AudioTags::Tags plain = AudioTags::read(path);
        CHECK(plain.artists.size() == 1);
        CHECK(plain.artist == QStringLiteral("Linkin Park;Jay-Z"));

        const AudioTags::Tags t = AudioTags::read(path, { QStringLiteral(";") });
        CHECK(t.artists.size() == 2);
        CHECK(t.artists.value(0) == QStringLiteral("Linkin Park"));
        CHECK(t.artists.value(1) == QStringLiteral("Jay-Z"));       // trimmed, and split without a space
        CHECK(t.genres.size() == 2);
        CHECK(t.genres.value(1) == QStringLiteral("Rock"));
        // ALBUM ARTIST IS NEVER SPLIT, whatever is in the separator list. It is the album grouping key, and
        // splitting it files one album per credited performer — #74's shattered album from the other side.
        CHECK(t.albumArtist == QStringLiteral("Linkin Park; Jay-Z"));
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("Linkin Park; Jay-Z"));
    }
    {
        // 6d. AC/DC. The name is not a list, and "/" is not in the default list precisely because of it. The
        //     same file read with "/" configured DOES split — the setting is real, and this is what it costs.
        QByteArray frames;
        frames.append(id3TextFrame("TIT2", QStringLiteral("Back in Black")));
        frames.append(id3TextFrame("TPE1", QStringLiteral("AC/DC")));
        frames.append(id3TextFrame("TALB", QStringLiteral("Back in Black")));

        const QString path = dir + QStringLiteral("/acdc.mp3");
        CHECK(writeFixture(path, mp3File(frames)));

        const AudioTags::Tags t = AudioTags::read(path, { QStringLiteral(";") });
        CHECK(t.artists.size() == 1);
        CHECK(t.artists.value(0) == QStringLiteral("AC/DC"));
        CHECK(t.artist == QStringLiteral("AC/DC"));
        CHECK(t.effectiveAlbumArtist() == QStringLiteral("AC/DC"));

        const AudioTags::Tags shredded = AudioTags::read(path, { QStringLiteral("/") });
        CHECK(shredded.artists.size() == 2);       // the documented cost of adding "/" — not the default
    }
    {
        // 6e. A STRUCTURED value is never re-split, even when the ad-hoc list would have cut it. The file
        //     said "these are two artists, and one of them is AC/DC"; re-splitting the container's own answer
        //     could only invent a band. This is the rule that makes 6d survivable for a "/" library.
        QList<QByteArray> comments;
        comments << QByteArray("ARTIST=AC/DC");
        comments << QByteArray("ARTIST=Queen");
        comments << QByteArray("ALBUM=Impossible Duets");

        QByteArray flac("fLaC", 4);
        flac.append(flacBlock(0, flacStreamInfo(44100, 2, 16, 132300), false));
        flac.append(flacBlock(4, flacVorbisComment(comments), true));

        const QString path = dir + QStringLiteral("/structured-slash.flac");
        CHECK(writeFixture(path, flac));

        const AudioTags::Tags t = AudioTags::read(path, { QStringLiteral("/") });
        CHECK(t.artists.size() == 2);
        CHECK(t.artists.value(0) == QStringLiteral("AC/DC"));   // intact, despite "/" being configured
        CHECK(t.artists.value(1) == QStringLiteral("Queen"));
    }
    {
        // 6f. A single artist is still a LIST OF ONE, so nothing downstream needs to know which shape it got.
        QByteArray frames;
        frames.append(id3TextFrame("TPE1", QStringLiteral("Portishead")));
        frames.append(id3TextFrame("TALB", QStringLiteral("Dummy")));
        const QString path = dir + QStringLiteral("/single.mp3");
        CHECK(writeFixture(path, mp3File(frames)));

        const AudioTags::Tags t = AudioTags::read(path, { QStringLiteral(";") });
        CHECK(t.artists.size() == 1);
        CHECK(t.artists.value(0) == QStringLiteral("Portishead"));
        CHECK(t.artist == QStringLiteral("Portishead"));    // display unchanged by having a list beside it
        CHECK(t.genres.isEmpty());                          // an untagged field yields NO values, not one empty
    }

    // --- 7. splitTagValues on its own — the rules, without a container in the way ------------------------
    {
        const QStringList semi  = { QStringLiteral(";") };
        const QStringList feat  = { QStringLiteral("feat.") };
        const QStringList both  = { QStringLiteral(";"), QStringLiteral("/"), QStringLiteral("feat.") };

        CHECK(AudioTags::splitTagValues(QStringLiteral("A;B"), semi) == QStringList({ QStringLiteral("A"), QStringLiteral("B") }));
        CHECK(AudioTags::splitTagValues(QStringLiteral(" A ; B "), semi) == QStringList({ QStringLiteral("A"), QStringLiteral("B") }));
        // No separators configured -> never split, whatever the string looks like. "Split nothing" has to be
        // expressible, because it is what an empty setting means.
        CHECK(AudioTags::splitTagValues(QStringLiteral("A;B"), {}) == QStringList({ QStringLiteral("A;B") }));

        // A LETTER separator needs whitespace on BOTH sides. Without that rule "feat." cuts "Featherstone"
        // in half and the library grows a band called "herstone Ensemble".
        CHECK(AudioTags::splitTagValues(QStringLiteral("Eminem feat. Dido"), feat)
              == QStringList({ QStringLiteral("Eminem"), QStringLiteral("Dido") }));
        CHECK(AudioTags::splitTagValues(QStringLiteral("Featherstone Ensemble"), feat)
              == QStringList({ QStringLiteral("Featherstone Ensemble") }));
        CHECK(AudioTags::splitTagValues(QStringLiteral("Defeat. Retreat."), feat)
              == QStringList({ QStringLiteral("Defeat. Retreat.") }));   // no leading whitespace before "feat."

        // Punctuation matches anywhere, which is the whole reason it is judged separately: "A;B" is how the
        // taggers that write a semicolon actually write it, and an anchored ';' would miss every one of them.
        CHECK(AudioTags::splitTagValues(QStringLiteral("Simon & Garfunkel"), both)
              == QStringList({ QStringLiteral("Simon & Garfunkel") }));  // '&' is not a separator here
        CHECK(AudioTags::splitTagValues(QStringLiteral("Emerson, Lake & Palmer"), both)
              == QStringList({ QStringLiteral("Emerson, Lake & Palmer") })); // nor is ','

        // Case-insensitive duplicates collapse to their first spelling: one row in a browse, not three.
        CHECK(AudioTags::splitTagValues(QStringLiteral("Bjork;BJORK;bjork"), semi)
              == QStringList({ QStringLiteral("Bjork") }));

        // Degenerate input never DELETES a credit: a value that is nothing but separators comes back whole,
        // because an unreadable artist is still browsable and a vanished one is not.
        CHECK(AudioTags::splitTagValues(QStringLiteral(";;;"), semi) == QStringList({ QStringLiteral(";;;") }));
        CHECK(AudioTags::splitTagValues(QStringLiteral("   "), semi).isEmpty());
        CHECK(AudioTags::splitTagValues(QString(), semi).isEmpty());
    }

    // --- 8. The extension filter the scan will apply before opening anything ------------------------------
    {
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.mp3")));
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.FLAC")));   // case-insensitive
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.m4a")));
        CHECK(AudioTags::isSupportedFile(QStringLiteral("/music/a.opus")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/cover.jpg")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/album.nfo")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/movies/film.mkv")));
        CHECK(!AudioTags::isSupportedFile(QStringLiteral("/music/no-extension")));
    }

    if (g_fails == 0)
        std::printf("MUSICTAGS-OK\n");
    else
        std::printf("MUSICTAGS had %d failure(s)\n", g_fails);
    return g_fails == 0 ? 0 : 1;
}
